_wandb:
    value:
        cli_version: 0.27.0
        e:
            zmpa1iqp7cm2vmto0ufrr6jx5hdk2a9o:
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1021821579264"
                        used: "259897270272"
                email: zied.marrakchi2001@gmail.com
                executable: C:\Users\ziedm\Refernce File\Studium\SoSe 26\DL BSA Project\repo\DL_BSA_F\.venv\Scripts\python.exe
                git:
                    commit: d8c8ee511749d716d14c72f183d4656b043372f2
                    remote: git@github.com:ZiedMarr/DL_BSA_F.git
                host: Zied-Thinkpad
                memory:
                    total: "33799254016"
                os: Windows-11-10.0.26200-SP0
                program: -m tests.test_wandb
                python: CPython 3.14.3
                root: C:\Users\ziedm\Refernce File\Studium\SoSe 26\DL BSA Project\repo\DL_BSA_F
                startedAt: "2026-06-09T16:23:15.866337Z"
                writerId: zmpa1iqp7cm2vmto0ufrr6jx5hdk2a9o
        m: []
        python_version: 3.14.3
        t:
            "3":
                - 2
                - 13
            "4": 3.14.3
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
